name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w" -o ./bin/shoya_amd64 .

      - name: Upload Shoya artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: shoya
          path: ./bin/shoya_amd64
          if-no-files-found: error